# Generated by Django 3.0.8 on 2021-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatestatus',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
