# Generated by Django 3.0.8 on 2021-09-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_estatestatus_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'managed': True},
        ),
    ]
