# Generated by Django 3.0.8 on 2021-09-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Broker'),
        ),
        migrations.AddField(
            model_name='contact',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Estate'),
        ),
        migrations.AddField(
            model_name='estate',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='estate_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.EstateStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.EstateType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('area_name', 'city')},
        ),
    ]
