# Generated by Django 3.0.8 on 2021-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210923_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatetype',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
