# Generated by Django 3.0.8 on 2021-09-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_estate_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='mobile',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
