# Generated by Django 3.0.8 on 2021-09-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20210924_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='broker',
            unique_together={('first_name', 'mobile')},
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=128)),
                ('pincode', models.IntegerField()),
                ('area', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='property.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Apartment')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='society',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='property.Apartment'),
        ),
    ]
