# Generated by Django 3.0.8 on 2021-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210924_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='city',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='area',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
