# Generated by Django 3.0.8 on 2021-09-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210924_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='pincode',
        ),
    ]
