# Generated by Django 3.0.8 on 2021-10-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20211026_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Broker'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Estate'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.City'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.EstateStatus'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.EstateType'),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Broker'),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Estate'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='estate_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='property.Estate'),
        ),
        migrations.AlterField(
            model_name='subestatetype',
            name='estate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.EstateType'),
        ),
    ]
